#
# Module manifest for module 'Az.Sql'
#
# Generated by: Microsoft Corporation
#
# Generated on: 5/14/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.Sql.psm1'

# Version number of this module.
ModuleVersion = '6.0.4'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f088f4ab-1b59-4836-a6e0-4e14d15800c6'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - SQL service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.

For more information on SQL, please visit the following: https://learn.microsoft.com/azure/sql-database/'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'Microsoft.Azure.PowerShell.Cmdlets.Sql.LegacySdk.dll', 
               'Microsoft.Azure.PowerShell.Sql.Management.Sdk.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'Sql.types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Sql.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Add-AzSqlDatabaseToFailoverGroup', 'Add-AzSqlElasticJobStep', 
               'Add-AzSqlElasticJobTarget', 'Add-AzSqlInstanceKeyVaultKey', 
               'Add-AzSqlManagedInstanceTransparentDataEncryptionCertificate', 
               'Add-AzSqlServerKeyVaultKey', 
               'Add-AzSqlServerTransparentDataEncryptionCertificate', 
               'Clear-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Clear-AzSqlDatabaseVulnerabilityAssessmentSetting', 
               'Clear-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Clear-AzSqlInstanceDatabaseVulnerabilityAssessmentSetting', 
               'Clear-AzSqlInstanceVulnerabilityAssessmentSetting', 
               'Clear-AzSqlServerVulnerabilityAssessmentSetting', 
               'Complete-AzSqlInstanceDatabaseCopy', 
               'Complete-AzSqlInstanceDatabaseLogReplay', 
               'Complete-AzSqlInstanceDatabaseMove', 
               'Convert-AzSqlDatabaseVulnerabilityAssessmentScan', 
               'Convert-AzSqlInstanceDatabaseVulnerabilityAssessmentScan', 
               'Copy-AzSqlDatabaseLongTermRetentionBackup', 
               'Copy-AzSqlInstanceDatabase', 
               'Disable-AzSqlDatabaseLedgerDigestUpload', 
               'Disable-AzSqlDatabaseSensitivityRecommendation', 
               'Disable-AzSqlInstanceActiveDirectoryOnlyAuthentication', 
               'Disable-AzSqlInstanceAdvancedDataSecurity', 
               'Disable-AzSqlInstanceDatabaseLedgerDigestUpload', 
               'Disable-AzSqlInstanceDatabaseSensitivityRecommendation', 
               'Disable-AzSqlServerActiveDirectoryOnlyAuthentication', 
               'Disable-AzSqlServerAdvancedDataSecurity', 
               'Enable-AzSqlDatabaseLedgerDigestUpload', 
               'Enable-AzSqlDatabaseSensitivityRecommendation', 
               'Enable-AzSqlInstanceActiveDirectoryOnlyAuthentication', 
               'Enable-AzSqlInstanceAdvancedDataSecurity', 
               'Enable-AzSqlInstanceDatabaseLedgerDigestUpload', 
               'Enable-AzSqlInstanceDatabaseSensitivityRecommendation', 
               'Enable-AzSqlServerActiveDirectoryOnlyAuthentication', 
               'Enable-AzSqlServerAdvancedDataSecurity', 'Get-AzSqlCapability', 
               'Get-AzSqlDatabase', 'Get-AzSqlDatabaseActivity', 
               'Get-AzSqlDatabaseAdvancedThreatProtectionSetting', 
               'Get-AzSqlDatabaseAdvisor', 'Get-AzSqlDatabaseAudit', 
               'Get-AzSqlDatabaseBackupLongTermRetentionPolicy', 
               'Get-AzSqlDatabaseBackupShortTermRetentionPolicy', 
               'Get-AzSqlDatabaseDataMaskingPolicy', 
               'Get-AzSqlDatabaseDataMaskingRule', 'Get-AzSqlDatabaseExpanded', 
               'Get-AzSqlDatabaseFailoverGroup', 'Get-AzSqlDatabaseGeoBackup', 
               'Get-AzSqlDatabaseGeoBackupPolicy', 
               'Get-AzSqlDatabaseImportExportStatus', 
               'Get-AzSqlDatabaseIndexRecommendation', 
               'Get-AzSqlDatabaseInstanceFailoverGroup', 
               'Get-AzSqlDatabaseLedgerDigestUpload', 
               'Get-AzSqlDatabaseLongTermRetentionBackup', 
               'Get-AzSqlDatabaseRecommendedAction', 
               'Get-AzSqlDatabaseReplicationLink', 'Get-AzSqlDatabaseRestorePoint', 
               'Set-AzSqlDatabaseReplicationLink', 
               'Get-AzSqlDatabaseSensitivityClassification', 
               'Get-AzSqlDatabaseSensitivityRecommendation', 
               'Get-AzSqlDatabaseTransparentDataEncryption', 
               'Get-AzSqlDatabaseUpgradeHint', 
               'Get-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Get-AzSqlDatabaseVulnerabilityAssessmentScanRecord', 
               'Get-AzSqlDatabaseVulnerabilityAssessmentSetting', 
               'Get-AzSqlDeletedDatabaseBackup', 
               'Get-AzSqlDeletedInstanceDatabaseBackup', 'Get-AzSqlElasticJob', 
               'Get-AzSqlElasticJobAgent', 'Get-AzSqlElasticJobCredential', 
               'Get-AzSqlElasticJobExecution', 
               'Get-AzSqlElasticJobPrivateEndpoint', 'Get-AzSqlElasticJobStep', 
               'Get-AzSqlElasticJobStepExecution', 
               'Get-AzSqlElasticJobTargetExecution', 
               'Get-AzSqlElasticJobTargetGroup', 'Get-AzSqlElasticPool', 
               'Get-AzSqlElasticPoolActivity', 'Get-AzSqlElasticPoolAdvisor', 
               'Get-AzSqlElasticPoolDatabase', 
               'Get-AzSqlElasticPoolRecommendation', 
               'Get-AzSqlElasticPoolRecommendedAction', 'Get-AzSqlInstance', 
               'Get-AzSqlInstanceActiveDirectoryAdministrator', 
               'Get-AzSqlInstanceActiveDirectoryOnlyAuthentication', 
               'Get-AzSqlInstanceAdvancedDataSecurityPolicy', 
               'Get-AzSqlInstanceAdvancedThreatProtectionSetting', 
               'Get-AzSqlInstanceDatabase', 
               'Get-AzSqlInstanceDatabaseAdvancedThreatProtectionSetting', 
               'Get-AzSqlInstanceDatabaseBackupLongTermRetentionPolicy', 
               'Get-AzSqlInstanceDatabaseBackupShortTermRetentionPolicy', 
               'Get-AzSqlInstanceDatabaseCopyOperation', 
               'Get-AzSqlInstanceDatabaseGeoBackup', 
               'Get-AzSqlInstanceDatabaseLedgerDigestUpload', 
               'Get-AzSqlInstanceDatabaseLogReplay', 
               'Get-AzSqlInstanceDatabaseLongTermRetentionBackup', 
               'Get-AzSqlInstanceDatabaseMoveOperation', 
               'Get-AzSqlInstanceDatabaseSensitivityClassification', 
               'Get-AzSqlInstanceDatabaseSensitivityRecommendation', 
               'Get-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Get-AzSqlInstanceDatabaseVulnerabilityAssessmentScanRecord', 
               'Get-AzSqlInstanceDatabaseVulnerabilityAssessmentSetting', 
               'Get-AzSqlInstanceDtc', 'Get-AzSqlInstanceEndpointCertificate', 
               'Get-AzSqlInstanceKeyVaultKey', 'Get-AzSqlInstanceLink', 
               'Get-AzSqlInstanceOperation', 'Get-AzSqlInstancePool', 
               'Get-AzSqlInstancePoolUsage', 
               'Get-AzSqlInstanceServerTrustCertificate', 
               'Get-AzSqlInstanceStartStopSchedule', 
               'Get-AzSqlInstanceTransparentDataEncryptionProtector', 
               'Get-AzSqlInstanceVulnerabilityAssessmentSetting', 
               'Get-AzSqlServer', 'Get-AzSqlServerActiveDirectoryAdministrator', 
               'Get-AzSqlServerActiveDirectoryOnlyAuthentication', 
               'Get-AzSqlServerAdvancedDataSecurityPolicy', 
               'Get-AzSqlServerAdvancedThreatProtectionSetting', 
               'Get-AzSqlServerAdvisor', 'Get-AzSqlServerAudit', 
               'Get-AzSqlServerCommunicationLink', 
               'Get-AzSqlServerConfigurationOption', 
               'Get-AzSqlServerDisasterRecoveryConfiguration', 
               'Get-AzSqlServerDisasterRecoveryConfigurationActivity', 
               'Get-AzSqlServerDnsAlias', 'Get-AzSqlServerFirewallRule', 
               'Get-AzSqlServerIpv6FirewallRule', 'Get-AzSqlServerKeyVaultKey', 
               'Get-AzSqlServerMSSupportAudit', 
               'Get-AzSqlServerOutboundFirewallRule', 
               'Get-AzSqlServerRecommendedAction', 
               'Get-AzSqlServerServiceObjective', 
               'Get-AzSqlServerTransparentDataEncryptionProtector', 
               'Get-AzSqlServerTrustGroup', 'Get-AzSqlServerUpgradeHint', 
               'Get-AzSqlServerVirtualNetworkRule', 
               'Get-AzSqlServerVulnerabilityAssessmentSetting', 
               'Get-AzSqlSyncAgent', 'Get-AzSqlSyncAgentLinkedDatabase', 
               'Get-AzSqlSyncGroup', 'Get-AzSqlSyncGroupLog', 'Get-AzSqlSyncMember', 
               'Get-AzSqlSyncSchema', 'Get-AzSqlVirtualCluster', 
               'Invoke-AzSqlDatabaseFailover', 'Start-AzSqlInstanceLinkFailover', 
               'Invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevalidation', 
               'Invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevert', 
               'Invoke-AzSqlElasticPoolFailover', 'Invoke-AzSqlInstanceFailover', 
               'Invoke-AzSqlInstanceExternalGovernanceStatusRefresh', 
               'Invoke-AzSqlInstanceTransparentDataEncryptionProtectorRevalidation', 
               'Invoke-AzSqlServerExternalGovernanceStatusRefresh', 
               'Invoke-AzSqlServerTransparentDataEncryptionProtectorRevalidation', 
               'Move-AzSqlInstanceDatabase', 'New-AzSqlDatabase', 
               'New-AzSqlDatabaseCopy', 'New-AzSqlDatabaseDataMaskingRule', 
               'New-AzSqlDatabaseExport', 'New-AzSqlDatabaseFailoverGroup', 
               'New-AzSqlDatabaseImport', 'New-AzSqlDatabaseInstanceFailoverGroup', 
               'New-AzSqlDatabaseRestorePoint', 'New-AzSqlDatabaseSecondary', 
               'New-AzSqlElasticJob', 'New-AzSqlElasticJobAgent', 
               'New-AzSqlElasticJobCredential', 
               'New-AzSqlElasticJobPrivateEndpoint', 
               'New-AzSqlElasticJobTargetGroup', 'New-AzSqlElasticPool', 
               'New-AzSqlInstance', 'New-AzSqlInstanceDatabase', 
               'New-AzSqlInstanceLink', 'New-AzSqlInstancePool', 
               'New-AzSqlInstanceScheduleItem', 
               'New-AzSqlInstanceServerTrustCertificate', 
               'New-AzSqlInstanceStartStopSchedule', 'New-AzSqlServer', 
               'New-AzSqlServerCommunicationLink', 
               'New-AzSqlServerDisasterRecoveryConfiguration', 
               'New-AzSqlServerDnsAlias', 'New-AzSqlServerFirewallRule', 
               'New-AzSqlServerIpv6FirewallRule', 
               'New-AzSqlServerOutboundFirewallRule', 'New-AzSqlServerTrustGroup', 
               'New-AzSqlServerVirtualNetworkRule', 'New-AzSqlSyncAgent', 
               'New-AzSqlSyncAgentKey', 'New-AzSqlSyncGroup', 'New-AzSqlSyncMember', 
               'Remove-AzSqlDatabase', 'Remove-AzSqlDatabaseAudit', 
               'Remove-AzSqlDatabaseDataMaskingRule', 
               'Remove-AzSqlDatabaseFailoverGroup', 
               'Remove-AzSqlDatabaseFromFailoverGroup', 
               'Remove-AzSqlDatabaseInstanceFailoverGroup', 
               'Remove-AzSqlDatabaseLongTermRetentionBackup', 
               'Remove-AzSqlDatabaseRestorePoint', 'Remove-AzSqlDatabaseSecondary', 
               'Remove-AzSqlDatabaseSensitivityClassification', 
               'Remove-AzSqlElasticJob', 'Remove-AzSqlElasticJobAgent', 
               'Remove-AzSqlElasticJobCredential', 
               'Remove-AzSqlElasticJobPrivateEndpoint', 
               'Remove-AzSqlElasticJobStep', 'Remove-AzSqlElasticJobTarget', 
               'Remove-AzSqlElasticJobTargetGroup', 'Remove-AzSqlElasticPool', 
               'Remove-AzSqlInstance', 
               'Remove-AzSqlInstanceActiveDirectoryAdministrator', 
               'Remove-AzSqlInstanceDatabase', 
               'Remove-AzSqlInstanceDatabaseLongTermRetentionBackup', 
               'Remove-AzSqlInstanceDatabaseSensitivityClassification', 
               'Remove-AzSqlInstanceKeyVaultKey', 'Remove-AzSqlInstanceLink', 
               'Remove-AzSqlInstancePool', 
               'Remove-AzSqlInstanceServerTrustCertificate', 
               'Remove-AzSqlInstanceStartStopSchedule', 'Remove-AzSqlServer', 
               'Remove-AzSqlServerActiveDirectoryAdministrator', 
               'Remove-AzSqlServerAudit', 'Remove-AzSqlServerCommunicationLink', 
               'Remove-AzSqlServerDisasterRecoveryConfiguration', 
               'Remove-AzSqlServerDnsAlias', 'Remove-AzSqlServerFirewallRule', 
               'Remove-AzSqlServerIpv6FirewallRule', 
               'Remove-AzSqlServerKeyVaultKey', 'Remove-AzSqlServerMSSupportAudit', 
               'Remove-AzSqlServerOutboundFirewallRule', 
               'Remove-AzSqlServerTrustGroup', 
               'Remove-AzSqlServerVirtualNetworkRule', 'Remove-AzSqlSyncAgent', 
               'Remove-AzSqlSyncGroup', 'Remove-AzSqlSyncMember', 
               'Remove-AzSqlVirtualCluster', 'Restore-AzSqlDatabase', 
               'Restore-AzSqlInstanceDatabase', 'Resume-AzSqlDatabase', 
               'Set-AzSqlDatabase', 'Set-AzSqlDatabaseAdvisorAutoExecuteStatus', 
               'Set-AzSqlDatabaseAudit', 
               'Set-AzSqlDatabaseBackupLongTermRetentionPolicy', 
               'Set-AzSqlDatabaseBackupShortTermRetentionPolicy', 
               'Set-AzSqlDatabaseDataMaskingPolicy', 
               'Set-AzSqlDatabaseDataMaskingRule', 
               'Set-AzSqlDatabaseFailoverGroup', 
               'Set-AzSqlDatabaseGeoBackupPolicy', 
               'Set-AzSqlDatabaseInstanceFailoverGroup', 
               'Set-AzSqlDatabaseRecommendedActionState', 
               'Set-AzSqlDatabaseSecondary', 
               'Set-AzSqlDatabaseSensitivityClassification', 
               'Set-AzSqlDatabaseTransparentDataEncryption', 
               'Set-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Set-AzSqlElasticJob', 'Set-AzSqlElasticJobAgent', 
               'Set-AzSqlElasticJobCredential', 'Set-AzSqlElasticJobStep', 
               'Set-AzSqlElasticPool', 
               'Set-AzSqlElasticPoolAdvisorAutoExecuteStatus', 
               'Set-AzSqlElasticPoolRecommendedActionState', 'Set-AzSqlInstance', 
               'Set-AzSqlInstanceActiveDirectoryAdministrator', 
               'Set-AzSqlInstanceDatabase', 
               'Set-AzSqlInstanceDatabaseBackupLongTermRetentionPolicy', 
               'Set-AzSqlInstanceDatabaseBackupShortTermRetentionPolicy', 
               'Set-AzSqlInstanceDatabaseSensitivityClassification', 
               'Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Set-AzSqlInstanceDtc', 'Set-AzSqlInstancePool', 
               'Set-AzSqlInstanceTransparentDataEncryptionProtector', 
               'Set-AzSqlServer', 'Set-AzSqlServerActiveDirectoryAdministrator', 
               'Set-AzSqlServerAdvisorAutoExecuteStatus', 'Set-AzSqlServerAudit', 
               'Set-AzSqlServerConfigurationOption', 
               'Set-AzSqlServerDisasterRecoveryConfiguration', 
               'Set-AzSqlServerDnsAlias', 'Set-AzSqlServerFirewallRule', 
               'Set-AzSqlServerIpv6FirewallRule', 'Set-AzSqlServerMSSupportAudit', 
               'Set-AzSqlServerRecommendedActionState', 
               'Set-AzSqlServerTransparentDataEncryptionProtector', 
               'Set-AzSqlServerVirtualNetworkRule', 
               'Start-AzSqlDatabaseExecuteIndexRecommendation', 
               'Start-AzSqlDatabaseVulnerabilityAssessmentScan', 
               'Start-AzSqlElasticJob', 'Start-AzSqlInstance', 
               'Start-AzSqlInstanceDatabaseLogReplay', 
               'Start-AzSqlInstanceDatabaseVulnerabilityAssessmentScan', 
               'Start-AzSqlSyncGroupSync', 'Stop-AzSqlDatabaseActivity', 
               'Stop-AzSqlDatabaseExecuteIndexRecommendation', 
               'Stop-AzSqlElasticJob', 'Stop-AzSqlElasticPoolActivity', 
               'Stop-AzSqlInstance', 'Stop-AzSqlInstanceDatabaseCopy', 
               'Stop-AzSqlInstanceDatabaseLogReplay', 
               'Stop-AzSqlInstanceDatabaseMove', 'Stop-AzSqlInstanceOperation', 
               'Stop-AzSqlSyncGroupSync', 'Suspend-AzSqlDatabase', 
               'Switch-AzSqlDatabaseFailoverGroup', 
               'Switch-AzSqlDatabaseInstanceFailoverGroup', 
               'Update-AzSqlDatabaseAdvancedThreatProtectionSetting', 
               'Update-AzSqlDatabaseLongTermRetentionBackup', 
               'Update-AzSqlDatabaseVulnerabilityAssessmentSetting', 
               'Update-AzSqlInstanceAdvancedThreatProtectionSetting', 
               'Update-AzSqlInstanceDatabaseAdvancedThreatProtectionSetting', 
               'Update-AzSqlInstanceDatabaseVulnerabilityAssessmentSetting', 
               'Update-AzSqlInstanceLink', 
               'Update-AzSqlInstanceVulnerabilityAssessmentSetting', 
               'Update-AzSqlServerAdvancedThreatProtectionSetting', 
               'Update-AzSqlServerVulnerabilityAssessmentSetting', 
               'Update-AzSqlSyncGroup', 'Update-AzSqlSyncMember', 
               'Update-AzSqlSyncSchema'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-AzSqlDatabaseLongTermRetentionPolicy', 
               'Get-AzSqlInstanceTDEProtector', 
               'Set-AzSqlDatabaseLongTermRetentionPolicy', 'Set-AzSqlInstanceLink', 
               'Set-AzSqlInstanceTDEProtector', 'Set-AzSqlServerTrustGroup'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '5.0.0'; })

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ResourceManager','ARM','Sql','Database'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Added server level action groups in enum of action groups to be able to be configured via auditing.'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoUgYJKoZIhvcNAQcCoIIoQzCCKD8CAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCnk73DKI6mzaTm
# LPXPbV6pMcywdACN4MFDEIZ+Ub/KBaCCDYUwggYDMIID66ADAgECAhMzAAAEA73V
# lV0POxitAAAAAAQDMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTEzWhcNMjUwOTExMjAxMTEzWjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQCfdGddwIOnbRYUyg03O3iz19XXZPmuhEmW/5uyEN+8mgxl+HJGeLGBR8YButGV
# LVK38RxcVcPYyFGQXcKcxgih4w4y4zJi3GvawLYHlsNExQwz+v0jgY/aejBS2EJY
# oUhLVE+UzRihV8ooxoftsmKLb2xb7BoFS6UAo3Zz4afnOdqI7FGoi7g4vx/0MIdi
# kwTn5N56TdIv3mwfkZCFmrsKpN0zR8HD8WYsvH3xKkG7u/xdqmhPPqMmnI2jOFw/
# /n2aL8W7i1Pasja8PnRXH/QaVH0M1nanL+LI9TsMb/enWfXOW65Gne5cqMN9Uofv
# ENtdwwEmJ3bZrcI9u4LZAkujAgMBAAGjggGCMIIBfjAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU6m4qAkpz4641iK2irF8eWsSBcBkw
# VAYDVR0RBE0wS6RJMEcxLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9wZXJh
# dGlvbnMgTGltaXRlZDEWMBQGA1UEBRMNMjMwMDEyKzUwMjkyNjAfBgNVHSMEGDAW
# gBRIbmTlUAXTgqoXNzcitW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8v
# d3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIw
# MTEtMDctMDguY3JsMGEGCCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDEx
# XzIwMTEtMDctMDguY3J0MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIB
# AFFo/6E4LX51IqFuoKvUsi80QytGI5ASQ9zsPpBa0z78hutiJd6w154JkcIx/f7r
# EBK4NhD4DIFNfRiVdI7EacEs7OAS6QHF7Nt+eFRNOTtgHb9PExRy4EI/jnMwzQJV
# NokTxu2WgHr/fBsWs6G9AcIgvHjWNN3qRSrhsgEdqHc0bRDUf8UILAdEZOMBvKLC
# rmf+kJPEvPldgK7hFO/L9kmcVe67BnKejDKO73Sa56AJOhM7CkeATrJFxO9GLXos
# oKvrwBvynxAg18W+pagTAkJefzneuWSmniTurPCUE2JnvW7DalvONDOtG01sIVAB
# +ahO2wcUPa2Zm9AiDVBWTMz9XUoKMcvngi2oqbsDLhbK+pYrRUgRpNt0y1sxZsXO
# raGRF8lM2cWvtEkV5UL+TQM1ppv5unDHkW8JS+QnfPbB8dZVRyRmMQ4aY/tx5x5+
# sX6semJ//FbiclSMxSI+zINu1jYerdUwuCi+P6p7SmQmClhDM+6Q+btE2FtpsU0W
# +r6RdYFf/P+nK6j2otl9Nvr3tWLu+WXmz8MGM+18ynJ+lYbSmFWcAj7SYziAfT0s
# IwlQRFkyC71tsIZUhBHtxPliGUu362lIO0Lpe0DOrg8lspnEWOkHnCT5JEnWCbzu
# iVt8RX1IV07uIveNZuOBWLVCzWJjEGa+HhaEtavjy6i7MIIHejCCBWKgAwIBAgIK
# YQ6Q0gAAAAAAAzANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNV
# BAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jv
# c29mdCBDb3Jwb3JhdGlvbjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlm
# aWNhdGUgQXV0aG9yaXR5IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEw
# OTA5WjB+MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYD
# VQQDEx9NaWNyb3NvZnQgQ29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG
# 9w0BAQEFAAOCAg8AMIICCgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+la
# UKq4BjgaBEm6f8MMHt03a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc
# 6Whe0t+bU7IKLMOv2akrrnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4D
# dato88tt8zpcoRb0RrrgOGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+
# lD3v++MrWhAfTVYoonpy4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nk
# kDstrjNYxbc+/jLTswM9sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6
# A4aN91/w0FK/jJSHvMAhdCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmd
# X4jiJV3TIUs+UsS1Vz8kA/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL
# 5zmhD+kjSbwYuER8ReTBw3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zd
# sGbiwZeBe+3W7UvnSSmnEyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3
# T8HhhUSJxAlMxdSlQy90lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS
# 4NaIjAsCAwEAAaOCAe0wggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRI
# bmTlUAXTgqoXNzcitW2oynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTAL
# BgNVHQ8EBAMCAYYwDwYDVR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBD
# uRQFTuHqp8cx0SOJNDBaBgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jv
# c29mdC5jb20vcGtpL2NybC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3JsMF4GCCsGAQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFf
# MDNfMjIuY3J0MIGfBgNVHSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEF
# BQcCARYzaHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1h
# cnljcHMuaHRtMEAGCCsGAQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkA
# YwB5AF8AcwB0AGEAdABlAG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn
# 8oalmOBUeRou09h0ZyKbC5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7
# v0epo/Np22O/IjWll11lhJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0b
# pdS1HXeUOeLpZMlEPXh6I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/
# KmtYSWMfCWluWpiW5IP0wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvy
# CInWH8MyGOLwxS3OW560STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBp
# mLJZiWhub6e3dMNABQamASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJi
# hsMdYzaXht/a8/jyFqGaJ+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYb
# BL7fQccOKO7eZS/sl/ahXJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbS
# oqKfenoi+kiVH6v7RyOA9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sL
# gOppO6/8MO0ETI7f33VtY5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtX
# cVZOSEXAQsmbdlsKgEhr/Xmfwb1tbWrJUnMTDXpQzTGCGiMwghofAgEBMIGVMH4x
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01p
# Y3Jvc29mdCBDb2RlIFNpZ25pbmcgUENBIDIwMTECEzMAAAQDvdWVXQ87GK0AAAAA
# BAMwDQYJYIZIAWUDBAIBBQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQw
# HAYKKwYBBAGCNwIBCzEOMAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIFGi
# SXgxVM8PiM+mKYew1BUeYAvv+w+hpG4Xhg15tA8iMEIGCisGAQQBgjcCAQwxNDAy
# oBSAEgBNAGkAYwByAG8AcwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20wDQYJKoZIhvcNAQEBBQAEggEAMErYz9jGcxpB3DZO/Zxv3D3hhoNuOHLRKT0l
# 4eiEZY3z8Cn9LlSeSpMP1z3ix2wlR9MrQQhrWqnlB7r4btHi2gOHybd19aiWKgbz
# 7Kc1du93rgHe2NXeAMPYnYG4j9bX8C9pCFoGRdmgIH34hbSkdXxK/RQ90WBXpM+F
# cw36jSTGOOmN3nvAAFYq1vQ+4rex2q0o5DfK711x8c1GRIFU0CcNuGkLmNjGTwX3
# Ai0W4twCi/bU/o62J/9biJ/vW21t/IbGikaRIhw5rcEK2hlb/PHjH3TNCoaDcAnF
# YoFNAyAvEEOvvUgYpptmis9sWUYK9LT/59AIrCuXyVc1WS/AIaGCF60wghepBgor
# BgEEAYI3AwMBMYIXmTCCF5UGCSqGSIb3DQEHAqCCF4YwgheCAgEDMQ8wDQYJYIZI
# AWUDBAIBBQAwggFaBgsqhkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGE
# WQoDATAxMA0GCWCGSAFlAwQCAQUABCDNaZLfUU+sfkXhppqzzvJQ9cg3uOvJsdc9
# DMIodw+O8AIGaBLCmswsGBMyMDI1MDUxNDA5MzgzOC4wNzdaMASAAgH0oIHZpIHW
# MIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
# Hm5TaGllbGQgVFNTIEVTTjozNjA1LTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
# b2Z0IFRpbWUtU3RhbXAgU2VydmljZaCCEfswggcoMIIFEKADAgECAhMzAAAB91gg
# dQTK+8L0AAEAAAH3MA0GCSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1w
# IFBDQSAyMDEwMB4XDTI0MDcyNTE4MzEwNloXDTI1MTAyMjE4MzEwNlowgdMxCzAJ
# BgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25k
# MR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jv
# c29mdCBJcmVsYW5kIE9wZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVs
# ZCBUU1MgRVNOOjM2MDUtMDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGlt
# ZS1TdGFtcCBTZXJ2aWNlMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA
# 0OdHTBNom6/uXKaEKP9rPITkT6QxF11tjzB0Nk1byDpPrFTHha3hxwSdTcr8Y0a3
# k6EQlwqy6ROz42e0R5eDW+dCoQapipDIFUOYp3oNuqwX/xepATEkY17MyXFx6rQW
# 2NcWUJW3Qo2AuJ0HOtblSpItQZPGmHnGqkt/DB45Fwxk6VoSvxNcQKhKETkuzrt8
# U6DRccQm1FdhmPKgDzgcfDPM5o+GnzbiMu6y069A4EHmLMmkecSkVvBmcZ8VnzFH
# TDkGLdpnDV5FXjVObAgbSM0cnqYSGfRp7VGHBRqyoscvR4bcQ+CV9pDjbJ6S5rZn
# 1uA8hRhj09Hs33HRevt4oWAVYGItgEsG+BrCYbpgWMDEIVnAgPZEiPAaI8wBGemE
# 4feEkuz7TAwgkRBcUzLgQ4uvPqRD1A+Jkt26+pDqWYSn0MA8j0zacQk9q/AvciPX
# D9It2ez+mqEzgFRRsJGLtcf9HksvK8Jsd6I5zFShlqi5bpzf1Y4NOiNOh5QwW1pI
# vA5irlal7qFhkAeeeZqmop8+uNxZXxFCQG3R3s5pXW89FiCh9rmXrVqOCwgcXFIJ
# QAQkllKsI+UJqGq9rmRABJz5lHKTFYmFwcM52KWWjNx3z6odwz2h+sxaxewToe9G
# qtDx3/aU+yqNRcB8w0tSXUf+ylN4uk5xHEpLpx+ZNNsCAwEAAaOCAUkwggFFMB0G
# A1UdDgQWBBTfRqQzP3m9PZWuLf1p8/meFfkmmDAfBgNVHSMEGDAWgBSfpxVdAF5i
# XYP05dJlpxtTNRnpcjBfBgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jv
# c29mdC5jb20vcGtpb3BzL2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENB
# JTIwMjAxMCgxKS5jcmwwbAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRw
# Oi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRp
# bWUtU3RhbXAlMjBQQ0ElMjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1Ud
# JQEB/wQMMAoGCCsGAQUFBwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsF
# AAOCAgEAN0ajafILeL6SQIMIMAXM1Qd6xaoci2mOrpR8vKWyyTsL3b83A7XGLiAb
# QxTrqnXvVWWeNst5YQD8saO+UTgOLJdTdfUADhLXoK+RlwjfndimIJT9MH9tUYXL
# zJXKhZM09ouPwNsrn8YOLIpdAi5TPyN8Cl11OGZSlP9r8JnvomW00AoJ4Pl9rlg0
# G5lcQknAXqHa9nQdWp1ZxXqNd+0JsKmlR8tcANX33ClM9NnaClJExLQHiKeHUUWt
# qyLMl65TW6wRM7XlF7Y+PTnC8duNWn4uLng+ON/Z39GO6qBj7IEZxoq4o3avEh9b
# a43UU6TgzVZaBm8VaA0wSwUe/pqpTOYFWN62XL3gl/JC2pzfIPxP66XfRLIxafjB
# VXm8KVDn2cML9IvRK02s941Y5+RR4gSAOhLiQQ6A03VNRup+spMa0k+XTPAi+2aM
# H5xa1Zjb/K8u9f9M05U0/bUMJXJDP++ysWpJbVRDiHG7szaca+r3HiUPjQJyQl2N
# iOcYTGV/DcLrLCBK2zG503FGb04N5Kf10XgAwFaXlod5B9eKh95PnXKx2LNBgLwG
# 85anlhhGxxBQ5mFsJGkBn0PZPtAzZyfr96qxzpp2pH9DJJcjKCDrMmZziXazpa5V
# VN36CO1kDU4ABkSYTXOM8RmJXuQm7mUF3bWmj+hjAJb4pz6hT5UwggdxMIIFWaAD
# AgECAhMzAAAAFcXna54Cm0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYD
# VQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEe
# MBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3Nv
# ZnQgUm9vdCBDZXJ0aWZpY2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIy
# MjVaFw0zMDA5MzAxODMyMjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNo
# aW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29y
# cG9yYXRpb24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEw
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5
# vQ7VgtP97pwHB9KpbE51yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64
# NmeFRiMMtY0Tz3cywBAY6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhu
# je3XD9gmU3w5YQJ6xKr9cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl
# 3GoPz130/o5Tz9bshVZN7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPg
# yY9+tVSP3PoFVZhtaDuaRr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I
# 5JasAUq7vnGpF1tnYN74kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2
# ci/bfV+AutuqfjbsNkz2K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/
# TNuvXsLz1dhzPUNOwTM5TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy
# 16cg8ML6EgrXY28MyTZki1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y
# 1BzFa/ZcUlFdEtsluq9QBXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6H
# XtqPnhZyacaue7e3PmriLq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMB
# AAEwIwYJKwYBBAGCNxUCBBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQW
# BBSfpxVdAF5iXYP05dJlpxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30B
# ATBBMD8GCCsGAQUFBwIBFjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L0RvY3MvUmVwb3NpdG9yeS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYB
# BAGCNxQCBAweCgBTAHUAYgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMB
# Af8wHwYDVR0jBBgwFoAU1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBL
# oEmgR4ZFaHR0cDovL2NybC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMv
# TWljUm9vQ2VyQXV0XzIwMTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggr
# BgEFBQcwAoY+aHR0cDovL3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNS
# b29DZXJBdXRfMjAxMC0wNi0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1Vffwq
# reEsH2cBMSRb4Z5yS/ypb+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27
# DzHkwo/7bNGhlBgi7ulmZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pv
# vinLbtg/SHUB2RjebYIM9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9Ak
# vUCgvxm2EhIRXT0n4ECWOKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWK
# NsIdw2FzLixre24/LAl4FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2
# kQH2zsZ0/fZMcm8Qq3UwxTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+
# c23Kjgm9swFXSVRk2XPXfx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep
# 8beuyOiJXk+d0tBMdrVXVAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+Dvk
# txW/tM4+pTFRhLy/AsGConsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1Zyvg
# DbjmjJnW4SLq8CdCPSWU5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/
# 2XBjU02N7oJtpQUQwXEGahC0HVUzWLOhcGbyoYIDVjCCAj4CAQEwggEBoYHZpIHW
# MIHTMQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMH
# UmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQL
# EyRNaWNyb3NvZnQgSXJlbGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsT
# Hm5TaGllbGQgVFNTIEVTTjozNjA1LTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9z
# b2Z0IFRpbWUtU3RhbXAgU2VydmljZaIjCgEBMAcGBSsOAwIaAxUAb28KDG/xXbNB
# jmM7/nqw3bgrEOaggYMwgYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2Fz
# aGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENv
# cnBvcmF0aW9uMSYwJAYDVQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAx
# MDANBgkqhkiG9w0BAQsFAAIFAOvOY8cwIhgPMjAyNTA1MTQwMDM1MTlaGA8yMDI1
# MDUxNTAwMzUxOVowdDA6BgorBgEEAYRZCgQBMSwwKjAKAgUA685jxwIBADAHAgEA
# AgIExjAHAgEAAgISXzAKAgUA68+1RwIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgor
# BgEEAYRZCgMCoAowCAIBAAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUA
# A4IBAQCXtze9Vm3WsfJZQ0AlZT7H/FAgl5/d2gEAcHr3J3h6mbZpFG7FjxHDyc9a
# W9Gf7UmHTzgc5kNe+ZNGu5IETPLK55vR43cWsI11pUMvXHIjoRBaa9RunQJR54Ja
# JHp6/bje+uHiPYXZ6uV2W5R9CmNOzedoimnIOaPYL/hvO5B/JUZwIv/+bAo/5ftW
# imlZyOyLXMvNUT3uklaKoyPTBfIZGr/O5Kmh4aAZkbyh/lwA/5CknvYmdxa94bUs
# uGaIBWgcpcFtV0HPoLpPe7R9al1oR7VLcKoPGXlezgMPpRCIpsrbSiqYWtFxmZna
# 3e5JR9UCeYfsNPzOAnhPNipYTbJeMYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMC
# VVMxEzARBgNVBAgTCldhc2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNV
# BAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRp
# bWUtU3RhbXAgUENBIDIwMTACEzMAAAH3WCB1BMr7wvQAAQAAAfcwDQYJYIZIAWUD
# BAIBBQCgggFKMBoGCSqGSIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0B
# CQQxIgQgrkMpoXFq6vFzIiZFGir15m6R2gkKr1xTmQ7YILqyC80wgfoGCyqGSIb3
# DQEJEAIvMYHqMIHnMIHkMIG9BCAh2pjaa3ca0ecYuhu60uYHP/IKnPbedbVQJ5So
# IH5Z4jCBmDCBgKR+MHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB
# 91ggdQTK+8L0AAEAAAH3MCIEINQw5I/LjZZMgtbG/2/FmXa92THNBKwKBUBQZE7c
# IQbhMA0GCSqGSIb3DQEBCwUABIICAHnU6xXFFEZdOiZm2PC4CdRjHTnXjADIcNun
# Z7aw0DdS2nocl9zd0snw9EObPtSlF2TSeZBJx7FCsRyYs6lmttElCWlIMdSVeV26
# hlAUdAdEWa2YRUB1jlr7vU4uzfK5caBqgHuKlC2SWqu9efH9sp58hMSrm+gAOasl
# iLsgn+guMAmr1Df7Jm4qaaNn09gr9I2c6F501fZ0KEL1ENoSNJlK/5YkVFEVw84O
# UNLjvc7q3w2EI3WrRiGjC954fd15MXjRYV1NmHkRf2mCpN5wZg5vmnEWz6ixDNpN
# Vva7B0Nb08NvtlwampkL8JUnpTaNK/DcnlwuOrZVBgEsw5+EzzmIwAx78Er7TfYF
# WiBEEUoUcc1R/DxVDuopEnexV8h0V6F+wzIuxVRhZY6pTBRqmvGWmeB+NGcuIlVP
# hkB7JRV/N1M18rwh0fuIv4n/nWuZ/1k0wYfIun/KIDkddWbUWdN6xBfYzmAqz9mG
# 7cVfxbVcf9SzfQI0HowttI9VmdG39oIwrIBCl7FzuGnSK5gIhWMA4MFicWi5aA3q
# geLlfPj5sLCThCLU+N88Zp9hsIvVpv3IjekojxQzMm16aMXQnbDcxvcNMXD4volo
# Ntso0TLjUy9YBTL+sdyCoB+NyiynBSaq4HTGFDmTqjv8Hl6DQh3uFk5M3Jq8KoX5
# g8MFCYPc
# SIG # End signature block
