#
# Module manifest for module 'Az.Sql'
#
# Generated by: Microsoft Corporation
#
# Generated on: 4/30/2025
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Az.Sql.psm1'

# Version number of this module.
ModuleVersion = '6.0.3'

# Supported PSEditions
CompatiblePSEditions = 'Core', 'Desktop'

# ID used to uniquely identify this module
GUID = 'f088f4ab-1b59-4836-a6e0-4e14d15800c6'

# Author of this module
Author = 'Microsoft Corporation'

# Company or vendor of this module
CompanyName = 'Microsoft Corporation'

# Copyright statement for this module
Copyright = 'Microsoft Corporation. All rights reserved.'

# Description of the functionality provided by this module
Description = 'Microsoft Azure PowerShell - SQL service cmdlets for Azure Resource Manager in Windows PowerShell and PowerShell Core.

For more information on SQL, please visit the following: https://learn.microsoft.com/azure/sql-database/'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
DotNetFrameworkVersion = '4.7.2'

# Minimum version of the common language runtime (CLR) required by this module. This prerequisite is valid for the PowerShell Desktop edition only.
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = 'Microsoft.Azure.PowerShell.Cmdlets.Sql.LegacySdk.dll', 
               'Microsoft.Azure.PowerShell.Sql.Management.Sdk.dll'

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = 'Sql.types.ps1xml'

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = 'Sql.format.ps1xml'

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
NestedModules = @()

# Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
FunctionsToExport = @()

# Cmdlets to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
CmdletsToExport = 'Add-AzSqlDatabaseToFailoverGroup', 'Add-AzSqlElasticJobStep', 
               'Add-AzSqlElasticJobTarget', 'Add-AzSqlInstanceKeyVaultKey', 
               'Add-AzSqlManagedInstanceTransparentDataEncryptionCertificate', 
               'Add-AzSqlServerKeyVaultKey', 
               'Add-AzSqlServerTransparentDataEncryptionCertificate', 
               'Clear-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Clear-AzSqlDatabaseVulnerabilityAssessmentSetting', 
               'Clear-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Clear-AzSqlInstanceDatabaseVulnerabilityAssessmentSetting', 
               'Clear-AzSqlInstanceVulnerabilityAssessmentSetting', 
               'Clear-AzSqlServerVulnerabilityAssessmentSetting', 
               'Complete-AzSqlInstanceDatabaseCopy', 
               'Complete-AzSqlInstanceDatabaseLogReplay', 
               'Complete-AzSqlInstanceDatabaseMove', 
               'Convert-AzSqlDatabaseVulnerabilityAssessmentScan', 
               'Convert-AzSqlInstanceDatabaseVulnerabilityAssessmentScan', 
               'Copy-AzSqlDatabaseLongTermRetentionBackup', 
               'Copy-AzSqlInstanceDatabase', 
               'Disable-AzSqlDatabaseLedgerDigestUpload', 
               'Disable-AzSqlDatabaseSensitivityRecommendation', 
               'Disable-AzSqlInstanceActiveDirectoryOnlyAuthentication', 
               'Disable-AzSqlInstanceAdvancedDataSecurity', 
               'Disable-AzSqlInstanceDatabaseLedgerDigestUpload', 
               'Disable-AzSqlInstanceDatabaseSensitivityRecommendation', 
               'Disable-AzSqlServerActiveDirectoryOnlyAuthentication', 
               'Disable-AzSqlServerAdvancedDataSecurity', 
               'Enable-AzSqlDatabaseLedgerDigestUpload', 
               'Enable-AzSqlDatabaseSensitivityRecommendation', 
               'Enable-AzSqlInstanceActiveDirectoryOnlyAuthentication', 
               'Enable-AzSqlInstanceAdvancedDataSecurity', 
               'Enable-AzSqlInstanceDatabaseLedgerDigestUpload', 
               'Enable-AzSqlInstanceDatabaseSensitivityRecommendation', 
               'Enable-AzSqlServerActiveDirectoryOnlyAuthentication', 
               'Enable-AzSqlServerAdvancedDataSecurity', 'Get-AzSqlCapability', 
               'Get-AzSqlDatabase', 'Get-AzSqlDatabaseActivity', 
               'Get-AzSqlDatabaseAdvancedThreatProtectionSetting', 
               'Get-AzSqlDatabaseAdvisor', 'Get-AzSqlDatabaseAudit', 
               'Get-AzSqlDatabaseBackupLongTermRetentionPolicy', 
               'Get-AzSqlDatabaseBackupShortTermRetentionPolicy', 
               'Get-AzSqlDatabaseDataMaskingPolicy', 
               'Get-AzSqlDatabaseDataMaskingRule', 'Get-AzSqlDatabaseExpanded', 
               'Get-AzSqlDatabaseFailoverGroup', 'Get-AzSqlDatabaseGeoBackup', 
               'Get-AzSqlDatabaseGeoBackupPolicy', 
               'Get-AzSqlDatabaseImportExportStatus', 
               'Get-AzSqlDatabaseIndexRecommendation', 
               'Get-AzSqlDatabaseInstanceFailoverGroup', 
               'Get-AzSqlDatabaseLedgerDigestUpload', 
               'Get-AzSqlDatabaseLongTermRetentionBackup', 
               'Get-AzSqlDatabaseRecommendedAction', 
               'Get-AzSqlDatabaseReplicationLink', 'Get-AzSqlDatabaseRestorePoint', 
               'Set-AzSqlDatabaseReplicationLink', 
               'Get-AzSqlDatabaseSensitivityClassification', 
               'Get-AzSqlDatabaseSensitivityRecommendation', 
               'Get-AzSqlDatabaseTransparentDataEncryption', 
               'Get-AzSqlDatabaseUpgradeHint', 
               'Get-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Get-AzSqlDatabaseVulnerabilityAssessmentScanRecord', 
               'Get-AzSqlDatabaseVulnerabilityAssessmentSetting', 
               'Get-AzSqlDeletedDatabaseBackup', 
               'Get-AzSqlDeletedInstanceDatabaseBackup', 'Get-AzSqlElasticJob', 
               'Get-AzSqlElasticJobAgent', 'Get-AzSqlElasticJobCredential', 
               'Get-AzSqlElasticJobExecution', 
               'Get-AzSqlElasticJobPrivateEndpoint', 'Get-AzSqlElasticJobStep', 
               'Get-AzSqlElasticJobStepExecution', 
               'Get-AzSqlElasticJobTargetExecution', 
               'Get-AzSqlElasticJobTargetGroup', 'Get-AzSqlElasticPool', 
               'Get-AzSqlElasticPoolActivity', 'Get-AzSqlElasticPoolAdvisor', 
               'Get-AzSqlElasticPoolDatabase', 
               'Get-AzSqlElasticPoolRecommendation', 
               'Get-AzSqlElasticPoolRecommendedAction', 'Get-AzSqlInstance', 
               'Get-AzSqlInstanceActiveDirectoryAdministrator', 
               'Get-AzSqlInstanceActiveDirectoryOnlyAuthentication', 
               'Get-AzSqlInstanceAdvancedDataSecurityPolicy', 
               'Get-AzSqlInstanceAdvancedThreatProtectionSetting', 
               'Get-AzSqlInstanceDatabase', 
               'Get-AzSqlInstanceDatabaseAdvancedThreatProtectionSetting', 
               'Get-AzSqlInstanceDatabaseBackupLongTermRetentionPolicy', 
               'Get-AzSqlInstanceDatabaseBackupShortTermRetentionPolicy', 
               'Get-AzSqlInstanceDatabaseCopyOperation', 
               'Get-AzSqlInstanceDatabaseGeoBackup', 
               'Get-AzSqlInstanceDatabaseLedgerDigestUpload', 
               'Get-AzSqlInstanceDatabaseLogReplay', 
               'Get-AzSqlInstanceDatabaseLongTermRetentionBackup', 
               'Get-AzSqlInstanceDatabaseMoveOperation', 
               'Get-AzSqlInstanceDatabaseSensitivityClassification', 
               'Get-AzSqlInstanceDatabaseSensitivityRecommendation', 
               'Get-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Get-AzSqlInstanceDatabaseVulnerabilityAssessmentScanRecord', 
               'Get-AzSqlInstanceDatabaseVulnerabilityAssessmentSetting', 
               'Get-AzSqlInstanceDtc', 'Get-AzSqlInstanceEndpointCertificate', 
               'Get-AzSqlInstanceKeyVaultKey', 'Get-AzSqlInstanceLink', 
               'Get-AzSqlInstanceOperation', 'Get-AzSqlInstancePool', 
               'Get-AzSqlInstancePoolUsage', 
               'Get-AzSqlInstanceServerTrustCertificate', 
               'Get-AzSqlInstanceStartStopSchedule', 
               'Get-AzSqlInstanceTransparentDataEncryptionProtector', 
               'Get-AzSqlInstanceVulnerabilityAssessmentSetting', 
               'Get-AzSqlServer', 'Get-AzSqlServerActiveDirectoryAdministrator', 
               'Get-AzSqlServerActiveDirectoryOnlyAuthentication', 
               'Get-AzSqlServerAdvancedDataSecurityPolicy', 
               'Get-AzSqlServerAdvancedThreatProtectionSetting', 
               'Get-AzSqlServerAdvisor', 'Get-AzSqlServerAudit', 
               'Get-AzSqlServerCommunicationLink', 
               'Get-AzSqlServerConfigurationOption', 
               'Get-AzSqlServerDisasterRecoveryConfiguration', 
               'Get-AzSqlServerDisasterRecoveryConfigurationActivity', 
               'Get-AzSqlServerDnsAlias', 'Get-AzSqlServerFirewallRule', 
               'Get-AzSqlServerIpv6FirewallRule', 'Get-AzSqlServerKeyVaultKey', 
               'Get-AzSqlServerMSSupportAudit', 
               'Get-AzSqlServerOutboundFirewallRule', 
               'Get-AzSqlServerRecommendedAction', 
               'Get-AzSqlServerServiceObjective', 
               'Get-AzSqlServerTransparentDataEncryptionProtector', 
               'Get-AzSqlServerTrustGroup', 'Get-AzSqlServerUpgradeHint', 
               'Get-AzSqlServerVirtualNetworkRule', 
               'Get-AzSqlServerVulnerabilityAssessmentSetting', 
               'Get-AzSqlSyncAgent', 'Get-AzSqlSyncAgentLinkedDatabase', 
               'Get-AzSqlSyncGroup', 'Get-AzSqlSyncGroupLog', 'Get-AzSqlSyncMember', 
               'Get-AzSqlSyncSchema', 'Get-AzSqlVirtualCluster', 
               'Invoke-AzSqlDatabaseFailover', 'Start-AzSqlInstanceLinkFailover', 
               'Invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevalidation', 
               'Invoke-AzSqlDatabaseTransparentDataEncryptionProtectorRevert', 
               'Invoke-AzSqlElasticPoolFailover', 'Invoke-AzSqlInstanceFailover', 
               'Invoke-AzSqlInstanceExternalGovernanceStatusRefresh', 
               'Invoke-AzSqlInstanceTransparentDataEncryptionProtectorRevalidation', 
               'Invoke-AzSqlServerExternalGovernanceStatusRefresh', 
               'Invoke-AzSqlServerTransparentDataEncryptionProtectorRevalidation', 
               'Move-AzSqlInstanceDatabase', 'New-AzSqlDatabase', 
               'New-AzSqlDatabaseCopy', 'New-AzSqlDatabaseDataMaskingRule', 
               'New-AzSqlDatabaseExport', 'New-AzSqlDatabaseFailoverGroup', 
               'New-AzSqlDatabaseImport', 'New-AzSqlDatabaseInstanceFailoverGroup', 
               'New-AzSqlDatabaseRestorePoint', 'New-AzSqlDatabaseSecondary', 
               'New-AzSqlElasticJob', 'New-AzSqlElasticJobAgent', 
               'New-AzSqlElasticJobCredential', 
               'New-AzSqlElasticJobPrivateEndpoint', 
               'New-AzSqlElasticJobTargetGroup', 'New-AzSqlElasticPool', 
               'New-AzSqlInstance', 'New-AzSqlInstanceDatabase', 
               'New-AzSqlInstanceLink', 'New-AzSqlInstancePool', 
               'New-AzSqlInstanceScheduleItem', 
               'New-AzSqlInstanceServerTrustCertificate', 
               'New-AzSqlInstanceStartStopSchedule', 'New-AzSqlServer', 
               'New-AzSqlServerCommunicationLink', 
               'New-AzSqlServerDisasterRecoveryConfiguration', 
               'New-AzSqlServerDnsAlias', 'New-AzSqlServerFirewallRule', 
               'New-AzSqlServerIpv6FirewallRule', 
               'New-AzSqlServerOutboundFirewallRule', 'New-AzSqlServerTrustGroup', 
               'New-AzSqlServerVirtualNetworkRule', 'New-AzSqlSyncAgent', 
               'New-AzSqlSyncAgentKey', 'New-AzSqlSyncGroup', 'New-AzSqlSyncMember', 
               'Remove-AzSqlDatabase', 'Remove-AzSqlDatabaseAudit', 
               'Remove-AzSqlDatabaseDataMaskingRule', 
               'Remove-AzSqlDatabaseFailoverGroup', 
               'Remove-AzSqlDatabaseFromFailoverGroup', 
               'Remove-AzSqlDatabaseInstanceFailoverGroup', 
               'Remove-AzSqlDatabaseLongTermRetentionBackup', 
               'Remove-AzSqlDatabaseRestorePoint', 'Remove-AzSqlDatabaseSecondary', 
               'Remove-AzSqlDatabaseSensitivityClassification', 
               'Remove-AzSqlElasticJob', 'Remove-AzSqlElasticJobAgent', 
               'Remove-AzSqlElasticJobCredential', 
               'Remove-AzSqlElasticJobPrivateEndpoint', 
               'Remove-AzSqlElasticJobStep', 'Remove-AzSqlElasticJobTarget', 
               'Remove-AzSqlElasticJobTargetGroup', 'Remove-AzSqlElasticPool', 
               'Remove-AzSqlInstance', 
               'Remove-AzSqlInstanceActiveDirectoryAdministrator', 
               'Remove-AzSqlInstanceDatabase', 
               'Remove-AzSqlInstanceDatabaseLongTermRetentionBackup', 
               'Remove-AzSqlInstanceDatabaseSensitivityClassification', 
               'Remove-AzSqlInstanceKeyVaultKey', 'Remove-AzSqlInstanceLink', 
               'Remove-AzSqlInstancePool', 
               'Remove-AzSqlInstanceServerTrustCertificate', 
               'Remove-AzSqlInstanceStartStopSchedule', 'Remove-AzSqlServer', 
               'Remove-AzSqlServerActiveDirectoryAdministrator', 
               'Remove-AzSqlServerAudit', 'Remove-AzSqlServerCommunicationLink', 
               'Remove-AzSqlServerDisasterRecoveryConfiguration', 
               'Remove-AzSqlServerDnsAlias', 'Remove-AzSqlServerFirewallRule', 
               'Remove-AzSqlServerIpv6FirewallRule', 
               'Remove-AzSqlServerKeyVaultKey', 'Remove-AzSqlServerMSSupportAudit', 
               'Remove-AzSqlServerOutboundFirewallRule', 
               'Remove-AzSqlServerTrustGroup', 
               'Remove-AzSqlServerVirtualNetworkRule', 'Remove-AzSqlSyncAgent', 
               'Remove-AzSqlSyncGroup', 'Remove-AzSqlSyncMember', 
               'Remove-AzSqlVirtualCluster', 'Restore-AzSqlDatabase', 
               'Restore-AzSqlInstanceDatabase', 'Resume-AzSqlDatabase', 
               'Set-AzSqlDatabase', 'Set-AzSqlDatabaseAdvisorAutoExecuteStatus', 
               'Set-AzSqlDatabaseAudit', 
               'Set-AzSqlDatabaseBackupLongTermRetentionPolicy', 
               'Set-AzSqlDatabaseBackupShortTermRetentionPolicy', 
               'Set-AzSqlDatabaseDataMaskingPolicy', 
               'Set-AzSqlDatabaseDataMaskingRule', 
               'Set-AzSqlDatabaseFailoverGroup', 
               'Set-AzSqlDatabaseGeoBackupPolicy', 
               'Set-AzSqlDatabaseInstanceFailoverGroup', 
               'Set-AzSqlDatabaseRecommendedActionState', 
               'Set-AzSqlDatabaseSecondary', 
               'Set-AzSqlDatabaseSensitivityClassification', 
               'Set-AzSqlDatabaseTransparentDataEncryption', 
               'Set-AzSqlDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Set-AzSqlElasticJob', 'Set-AzSqlElasticJobAgent', 
               'Set-AzSqlElasticJobCredential', 'Set-AzSqlElasticJobStep', 
               'Set-AzSqlElasticPool', 
               'Set-AzSqlElasticPoolAdvisorAutoExecuteStatus', 
               'Set-AzSqlElasticPoolRecommendedActionState', 'Set-AzSqlInstance', 
               'Set-AzSqlInstanceActiveDirectoryAdministrator', 
               'Set-AzSqlInstanceDatabase', 
               'Set-AzSqlInstanceDatabaseBackupLongTermRetentionPolicy', 
               'Set-AzSqlInstanceDatabaseBackupShortTermRetentionPolicy', 
               'Set-AzSqlInstanceDatabaseSensitivityClassification', 
               'Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline', 
               'Set-AzSqlInstanceDtc', 'Set-AzSqlInstancePool', 
               'Set-AzSqlInstanceTransparentDataEncryptionProtector', 
               'Set-AzSqlServer', 'Set-AzSqlServerActiveDirectoryAdministrator', 
               'Set-AzSqlServerAdvisorAutoExecuteStatus', 'Set-AzSqlServerAudit', 
               'Set-AzSqlServerConfigurationOption', 
               'Set-AzSqlServerDisasterRecoveryConfiguration', 
               'Set-AzSqlServerDnsAlias', 'Set-AzSqlServerFirewallRule', 
               'Set-AzSqlServerIpv6FirewallRule', 'Set-AzSqlServerMSSupportAudit', 
               'Set-AzSqlServerRecommendedActionState', 
               'Set-AzSqlServerTransparentDataEncryptionProtector', 
               'Set-AzSqlServerVirtualNetworkRule', 
               'Start-AzSqlDatabaseExecuteIndexRecommendation', 
               'Start-AzSqlDatabaseVulnerabilityAssessmentScan', 
               'Start-AzSqlElasticJob', 'Start-AzSqlInstance', 
               'Start-AzSqlInstanceDatabaseLogReplay', 
               'Start-AzSqlInstanceDatabaseVulnerabilityAssessmentScan', 
               'Start-AzSqlSyncGroupSync', 'Stop-AzSqlDatabaseActivity', 
               'Stop-AzSqlDatabaseExecuteIndexRecommendation', 
               'Stop-AzSqlElasticJob', 'Stop-AzSqlElasticPoolActivity', 
               'Stop-AzSqlInstance', 'Stop-AzSqlInstanceDatabaseCopy', 
               'Stop-AzSqlInstanceDatabaseLogReplay', 
               'Stop-AzSqlInstanceDatabaseMove', 'Stop-AzSqlInstanceOperation', 
               'Stop-AzSqlSyncGroupSync', 'Suspend-AzSqlDatabase', 
               'Switch-AzSqlDatabaseFailoverGroup', 
               'Switch-AzSqlDatabaseInstanceFailoverGroup', 
               'Update-AzSqlDatabaseAdvancedThreatProtectionSetting', 
               'Update-AzSqlDatabaseLongTermRetentionBackup', 
               'Update-AzSqlDatabaseVulnerabilityAssessmentSetting', 
               'Update-AzSqlInstanceAdvancedThreatProtectionSetting', 
               'Update-AzSqlInstanceDatabaseAdvancedThreatProtectionSetting', 
               'Update-AzSqlInstanceDatabaseVulnerabilityAssessmentSetting', 
               'Update-AzSqlInstanceLink', 
               'Update-AzSqlInstanceVulnerabilityAssessmentSetting', 
               'Update-AzSqlServerAdvancedThreatProtectionSetting', 
               'Update-AzSqlServerVulnerabilityAssessmentSetting', 
               'Update-AzSqlSyncGroup', 'Update-AzSqlSyncMember', 
               'Update-AzSqlSyncSchema'

# Variables to export from this module
# VariablesToExport = @()

# Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
AliasesToExport = 'Get-AzSqlDatabaseLongTermRetentionPolicy', 
               'Get-AzSqlInstanceTDEProtector', 
               'Set-AzSqlDatabaseLongTermRetentionPolicy', 'Set-AzSqlInstanceLink', 
               'Set-AzSqlInstanceTDEProtector', 'Set-AzSqlServerTrustGroup'

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
ModuleList = @(@{ModuleName = 'Az.Accounts'; ModuleVersion = '4.2.0'; })

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
PrivateData = @{

    PSData = @{

        # Tags applied to this module. These help with module discovery in online galleries.
        Tags = 'Azure','ResourceManager','ARM','Sql','Database'

        # A URL to the license for this module.
        LicenseUri = 'https://aka.ms/azps-license'

        # A URL to the main website for this project.
        ProjectUri = 'https://github.com/Azure/azure-powershell'

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = '* Added Information message to ''Set-AzSqlInstance'' for migrating Azure Sql database with GeoDr links to Azure Sql Hyperscale Edition'

        # Prerelease string of this module
        # Prerelease = ''

        # Flag to indicate whether the module requires explicit user acceptance for install/update/save
        # RequireLicenseAcceptance = $false

        # External dependent modules of this module
        # ExternalModuleDependencies = @()

    } # End of PSData hashtable

 } # End of PrivateData hashtable

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}


# SIG # Begin signature block
# MIIoQwYJKoZIhvcNAQcCoIIoNDCCKDACAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCU0Sp0IDZPGstA
# pUyA6X/QpX1QsSTEt433JK75lIEzSKCCDXYwggX0MIID3KADAgECAhMzAAAEBGx0
# Bv9XKydyAAAAAAQEMA0GCSqGSIb3DQEBCwUAMH4xCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNpZ25p
# bmcgUENBIDIwMTEwHhcNMjQwOTEyMjAxMTE0WhcNMjUwOTExMjAxMTE0WjB0MQsw
# CQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9u
# ZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMR4wHAYDVQQDExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIB
# AQC0KDfaY50MDqsEGdlIzDHBd6CqIMRQWW9Af1LHDDTuFjfDsvna0nEuDSYJmNyz
# NB10jpbg0lhvkT1AzfX2TLITSXwS8D+mBzGCWMM/wTpciWBV/pbjSazbzoKvRrNo
# DV/u9omOM2Eawyo5JJJdNkM2d8qzkQ0bRuRd4HarmGunSouyb9NY7egWN5E5lUc3
# a2AROzAdHdYpObpCOdeAY2P5XqtJkk79aROpzw16wCjdSn8qMzCBzR7rvH2WVkvF
# HLIxZQET1yhPb6lRmpgBQNnzidHV2Ocxjc8wNiIDzgbDkmlx54QPfw7RwQi8p1fy
# 4byhBrTjv568x8NGv3gwb0RbAgMBAAGjggFzMIIBbzAfBgNVHSUEGDAWBgorBgEE
# AYI3TAgBBggrBgEFBQcDAzAdBgNVHQ4EFgQU8huhNbETDU+ZWllL4DNMPCijEU4w
# RQYDVR0RBD4wPKQ6MDgxHjAcBgNVBAsTFU1pY3Jvc29mdCBDb3Jwb3JhdGlvbjEW
# MBQGA1UEBRMNMjMwMDEyKzUwMjkyMzAfBgNVHSMEGDAWgBRIbmTlUAXTgqoXNzci
# tW2oynUClTBUBgNVHR8ETTBLMEmgR6BFhkNodHRwOi8vd3d3Lm1pY3Jvc29mdC5j
# b20vcGtpb3BzL2NybC9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3JsMGEG
# CCsGAQUFBwEBBFUwUzBRBggrBgEFBQcwAoZFaHR0cDovL3d3dy5taWNyb3NvZnQu
# Y29tL3BraW9wcy9jZXJ0cy9NaWNDb2RTaWdQQ0EyMDExXzIwMTEtMDctMDguY3J0
# MAwGA1UdEwEB/wQCMAAwDQYJKoZIhvcNAQELBQADggIBAIjmD9IpQVvfB1QehvpC
# Ge7QeTQkKQ7j3bmDMjwSqFL4ri6ae9IFTdpywn5smmtSIyKYDn3/nHtaEn0X1NBj
# L5oP0BjAy1sqxD+uy35B+V8wv5GrxhMDJP8l2QjLtH/UglSTIhLqyt8bUAqVfyfp
# h4COMRvwwjTvChtCnUXXACuCXYHWalOoc0OU2oGN+mPJIJJxaNQc1sjBsMbGIWv3
# cmgSHkCEmrMv7yaidpePt6V+yPMik+eXw3IfZ5eNOiNgL1rZzgSJfTnvUqiaEQ0X
# dG1HbkDv9fv6CTq6m4Ty3IzLiwGSXYxRIXTxT4TYs5VxHy2uFjFXWVSL0J2ARTYL
# E4Oyl1wXDF1PX4bxg1yDMfKPHcE1Ijic5lx1KdK1SkaEJdto4hd++05J9Bf9TAmi
# u6EK6C9Oe5vRadroJCK26uCUI4zIjL/qG7mswW+qT0CW0gnR9JHkXCWNbo8ccMk1
# sJatmRoSAifbgzaYbUz8+lv+IXy5GFuAmLnNbGjacB3IMGpa+lbFgih57/fIhamq
# 5VhxgaEmn/UjWyr+cPiAFWuTVIpfsOjbEAww75wURNM1Imp9NJKye1O24EspEHmb
# DmqCUcq7NqkOKIG4PVm3hDDED/WQpzJDkvu4FrIbvyTGVU01vKsg4UfcdiZ0fQ+/
# V0hf8yrtq9CkB8iIuk5bBxuPMIIHejCCBWKgAwIBAgIKYQ6Q0gAAAAAAAzANBgkq
# hkiG9w0BAQsFADCBiDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldhc2hpbmd0b24x
# EDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBDb3Jwb3JhdGlv
# bjEyMDAGA1UEAxMpTWljcm9zb2Z0IFJvb3QgQ2VydGlmaWNhdGUgQXV0aG9yaXR5
# IDIwMTEwHhcNMTEwNzA4MjA1OTA5WhcNMjYwNzA4MjEwOTA5WjB+MQswCQYDVQQG
# EwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwG
# A1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSgwJgYDVQQDEx9NaWNyb3NvZnQg
# Q29kZSBTaWduaW5nIFBDQSAyMDExMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIIC
# CgKCAgEAq/D6chAcLq3YbqqCEE00uvK2WCGfQhsqa+laUKq4BjgaBEm6f8MMHt03
# a8YS2AvwOMKZBrDIOdUBFDFC04kNeWSHfpRgJGyvnkmc6Whe0t+bU7IKLMOv2akr
# rnoJr9eWWcpgGgXpZnboMlImEi/nqwhQz7NEt13YxC4Ddato88tt8zpcoRb0Rrrg
# OGSsbmQ1eKagYw8t00CT+OPeBw3VXHmlSSnnDb6gE3e+lD3v++MrWhAfTVYoonpy
# 4BI6t0le2O3tQ5GD2Xuye4Yb2T6xjF3oiU+EGvKhL1nkkDstrjNYxbc+/jLTswM9
# sbKvkjh+0p2ALPVOVpEhNSXDOW5kf1O6nA+tGSOEy/S6A4aN91/w0FK/jJSHvMAh
# dCVfGCi2zCcoOCWYOUo2z3yxkq4cI6epZuxhH2rhKEmdX4jiJV3TIUs+UsS1Vz8k
# A/DRelsv1SPjcF0PUUZ3s/gA4bysAoJf28AVs70b1FVL5zmhD+kjSbwYuER8ReTB
# w3J64HLnJN+/RpnF78IcV9uDjexNSTCnq47f7Fufr/zdsGbiwZeBe+3W7UvnSSmn
# Eyimp31ngOaKYnhfsi+E11ecXL93KCjx7W3DKI8sj0A3T8HhhUSJxAlMxdSlQy90
# lfdu+HggWCwTXWCVmj5PM4TasIgX3p5O9JawvEagbJjS4NaIjAsCAwEAAaOCAe0w
# ggHpMBAGCSsGAQQBgjcVAQQDAgEAMB0GA1UdDgQWBBRIbmTlUAXTgqoXNzcitW2o
# ynUClTAZBgkrBgEEAYI3FAIEDB4KAFMAdQBiAEMAQTALBgNVHQ8EBAMCAYYwDwYD
# VR0TAQH/BAUwAwEB/zAfBgNVHSMEGDAWgBRyLToCMZBDuRQFTuHqp8cx0SOJNDBa
# BgNVHR8EUzBRME+gTaBLhklodHRwOi8vY3JsLm1pY3Jvc29mdC5jb20vcGtpL2Ny
# bC9wcm9kdWN0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3JsMF4GCCsG
# AQUFBwEBBFIwUDBOBggrBgEFBQcwAoZCaHR0cDovL3d3dy5taWNyb3NvZnQuY29t
# L3BraS9jZXJ0cy9NaWNSb29DZXJBdXQyMDExXzIwMTFfMDNfMjIuY3J0MIGfBgNV
# HSAEgZcwgZQwgZEGCSsGAQQBgjcuAzCBgzA/BggrBgEFBQcCARYzaHR0cDovL3d3
# dy5taWNyb3NvZnQuY29tL3BraW9wcy9kb2NzL3ByaW1hcnljcHMuaHRtMEAGCCsG
# AQUFBwICMDQeMiAdAEwAZQBnAGEAbABfAHAAbwBsAGkAYwB5AF8AcwB0AGEAdABl
# AG0AZQBuAHQALiAdMA0GCSqGSIb3DQEBCwUAA4ICAQBn8oalmOBUeRou09h0ZyKb
# C5YR4WOSmUKWfdJ5DJDBZV8uLD74w3LRbYP+vj/oCso7v0epo/Np22O/IjWll11l
# hJB9i0ZQVdgMknzSGksc8zxCi1LQsP1r4z4HLimb5j0bpdS1HXeUOeLpZMlEPXh6
# I/MTfaaQdION9MsmAkYqwooQu6SpBQyb7Wj6aC6VoCo/KmtYSWMfCWluWpiW5IP0
# wI/zRive/DvQvTXvbiWu5a8n7dDd8w6vmSiXmE0OPQvyCInWH8MyGOLwxS3OW560
# STkKxgrCxq2u5bLZ2xWIUUVYODJxJxp/sfQn+N4sOiBpmLJZiWhub6e3dMNABQam
# ASooPoI/E01mC8CzTfXhj38cbxV9Rad25UAqZaPDXVJihsMdYzaXht/a8/jyFqGa
# J+HNpZfQ7l1jQeNbB5yHPgZ3BtEGsXUfFL5hYbXw3MYbBL7fQccOKO7eZS/sl/ah
# XJbYANahRr1Z85elCUtIEJmAH9AAKcWxm6U/RXceNcbSoqKfenoi+kiVH6v7RyOA
# 9Z74v2u3S5fi63V4GuzqN5l5GEv/1rMjaHXmr/r8i+sLgOppO6/8MO0ETI7f33Vt
# Y5E90Z1WTk+/gFcioXgRMiF670EKsT/7qMykXcGhiJtXcVZOSEXAQsmbdlsKgEhr
# /Xmfwb1tbWrJUnMTDXpQzTGCGiMwghofAgEBMIGVMH4xCzAJBgNVBAYTAlVTMRMw
# EQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVN
# aWNyb3NvZnQgQ29ycG9yYXRpb24xKDAmBgNVBAMTH01pY3Jvc29mdCBDb2RlIFNp
# Z25pbmcgUENBIDIwMTECEzMAAAQEbHQG/1crJ3IAAAAABAQwDQYJYIZIAWUDBAIB
# BQCgga4wGQYJKoZIhvcNAQkDMQwGCisGAQQBgjcCAQQwHAYKKwYBBAGCNwIBCzEO
# MAwGCisGAQQBgjcCARUwLwYJKoZIhvcNAQkEMSIEIKAV6cWA9JiiVObe57NMrz0p
# a9kb0od3njPpzgMFPIjpMEIGCisGAQQBgjcCAQwxNDAyoBSAEgBNAGkAYwByAG8A
# cwBvAGYAdKEagBhodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20wDQYJKoZIhvcNAQEB
# BQAEggEAAHiDIGDt5LzXE5bvjJsCFtWDl684U/fAe4br/I7NF3PTjHTofiRtlozt
# MselQLbIQPfPnfe8ph/UnrUfAkPByetZOKh93S9jljGyQUogCnwx48qcIcY+66aA
# 94U5S2L+81NmdWel1j+HwHBdsNNgkpX1rrVY9API/0qaFRlGtnGXRDNO/+HFLfRk
# xRJasrwzArEtFR0fbBU++3NcugWP6M4jDC+mMdY6SsTBtScvdCrpSdI10SUNaYDN
# WhdS/X5kyHDIDurlJUHjv0EzVJrEYyXmfJviDVTO0MVLEUPS3/zKaQ1n7wO3RGBk
# w4Zv2mAe0qHsYOOwlv+L/hF/f1K/EaGCF60wghepBgorBgEEAYI3AwMBMYIXmTCC
# F5UGCSqGSIb3DQEHAqCCF4YwgheCAgEDMQ8wDQYJYIZIAWUDBAIBBQAwggFaBgsq
# hkiG9w0BCRABBKCCAUkEggFFMIIBQQIBAQYKKwYBBAGEWQoDATAxMA0GCWCGSAFl
# AwQCAQUABCAt49A7faHwf7dsPVx4UH9JbuW6+bStKL4s4ce7oirDSgIGaAsnDcSF
# GBMyMDI1MDQzMDAyNTcyOS40ODVaMASAAgH0oIHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo2RjFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaCCEfswggcoMIIFEKADAgECAhMzAAAB/Bigr8xpWoc6AAEAAAH8MA0G
# CSqGSIb3DQEBCwUAMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9u
# MRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRp
# b24xJjAkBgNVBAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMB4XDTI0
# MDcyNTE4MzExNFoXDTI1MTAyMjE4MzExNFowgdMxCzAJBgNVBAYTAlVTMRMwEQYD
# VQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRtb25kMR4wHAYDVQQKExVNaWNy
# b3NvZnQgQ29ycG9yYXRpb24xLTArBgNVBAsTJE1pY3Jvc29mdCBJcmVsYW5kIE9w
# ZXJhdGlvbnMgTGltaXRlZDEnMCUGA1UECxMeblNoaWVsZCBUU1MgRVNOOjZGMUEt
# MDVFMC1EOTQ3MSUwIwYDVQQDExxNaWNyb3NvZnQgVGltZS1TdGFtcCBTZXJ2aWNl
# MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAp1DAKLxpbQcPVYPHlJHy
# W7W5lBZjJWWDjMfl5WyhuAylP/LDm2hb4ymUmSymV0EFRQcmM8BypwjhWP8F7x4i
# O88d+9GZ9MQmNh3jSDohhXXgf8rONEAyfCPVmJzM7ytsurZ9xocbuEL7+P7EkIwo
# OuMFlTF2G/zuqx1E+wANslpPqPpb8PC56BQxgJCI1LOF5lk3AePJ78OL3aw/Ndlk
# vdVl3VgBSPX4Nawt3UgUofuPn/cp9vwKKBwuIWQEFZ837GXXITshd2Mfs6oYfxXE
# tmj2SBGEhxVs7xERuWGb0cK6afy7naKkbZI2v1UqsxuZt94rn/ey2ynvunlx0R6/
# b6nNkC1rOTAfWlpsAj/QlzyM6uYTSxYZC2YWzLbbRl0lRtSz+4TdpUU/oAZSB+Y+
# s12Rqmgzi7RVxNcI2lm//sCEm6A63nCJCgYtM+LLe9pTshl/Wf8OOuPQRiA+stTs
# g89BOG9tblaz2kfeOkYf5hdH8phAbuOuDQfr6s5Ya6W+vZz6E0Zsenzi0OtMf5RC
# a2hADYVgUxD+grC8EptfWeVAWgYCaQFheNN/ZGNQMkk78V63yoPBffJEAu+B5xlT
# PYoijUdo9NXovJmoGXj6R8Tgso+QPaAGHKxCbHa1QL9ASMF3Os1jrogCHGiykfp1
# dKGnmA5wJT6Nx7BedlSDsAkCAwEAAaOCAUkwggFFMB0GA1UdDgQWBBSY8aUrsUaz
# hxByH79dhiQCL/7QdjAfBgNVHSMEGDAWgBSfpxVdAF5iXYP05dJlpxtTNRnpcjBf
# BgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3Bz
# L2NybC9NaWNyb3NvZnQlMjBUaW1lLVN0YW1wJTIwUENBJTIwMjAxMCgxKS5jcmww
# bAYIKwYBBQUHAQEEYDBeMFwGCCsGAQUFBzAChlBodHRwOi8vd3d3Lm1pY3Jvc29m
# dC5jb20vcGtpb3BzL2NlcnRzL01pY3Jvc29mdCUyMFRpbWUtU3RhbXAlMjBQQ0El
# MjAyMDEwKDEpLmNydDAMBgNVHRMBAf8EAjAAMBYGA1UdJQEB/wQMMAoGCCsGAQUF
# BwMIMA4GA1UdDwEB/wQEAwIHgDANBgkqhkiG9w0BAQsFAAOCAgEAT7ss/ZAZ0bTa
# FsrsiJYd//LQ6ImKb9JZSKiRw9xs8hwk5Y/7zign9gGtweRChC2lJ8GVRHgrFkBx
# ACjuuPprSz/UYX7n522JKcudnWuIeE1p30BZrqPTOnscD98DZi6WNTAymnaS7it5
# qAgNInreAJbTU2cAosJoeXAHr50YgSGlmJM+cN6mYLAL6TTFMtFYJrpK9TM5Ryh5
# eZmm6UTJnGg0jt1pF/2u8PSdz3dDy7DF7KDJad2qHxZORvM3k9V8Yn3JI5YLPuLs
# o2J5s3fpXyCVgR/hq86g5zjd9bRRyyiC8iLIm/N95q6HWVsCeySetrqfsDyYWStw
# L96hy7DIyLL5ih8YFMd0AdmvTRoylmADuKwE2TQCTvPnjnLk7ypJW29t17Yya4V+
# Jlz54sBnPU7kIeYZsvUT+YKgykP1QB+p+uUdRH6e79Vaiz+iewWrIJZ4tXkDMmL2
# 1nh0j+58E1ecAYDvT6B4yFIeonxA/6Gl9Xs7JLciPCIC6hGdliiEBpyYeUF0ohZF
# n7NKQu80IZ0jd511WA2bq6x9aUq/zFyf8Egw+dunUj1KtNoWpq7VuJqapckYsmvm
# mYHZXCjK1Eus7V1I+aXjrBYuqyM9QpeFZU4U01YG15uWwUCaj0uZlah/RGSYMd84
# y9DCqOpfeKE6PLMk7hLnhvcOQrnxP6kwggdxMIIFWaADAgECAhMzAAAAFcXna54C
# m0mZAAAAAAAVMA0GCSqGSIb3DQEBCwUAMIGIMQswCQYDVQQGEwJVUzETMBEGA1UE
# CBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9z
# b2Z0IENvcnBvcmF0aW9uMTIwMAYDVQQDEylNaWNyb3NvZnQgUm9vdCBDZXJ0aWZp
# Y2F0ZSBBdXRob3JpdHkgMjAxMDAeFw0yMTA5MzAxODIyMjVaFw0zMDA5MzAxODMy
# MjVaMHwxCzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQH
# EwdSZWRtb25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNV
# BAMTHU1pY3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwMIICIjANBgkqhkiG9w0B
# AQEFAAOCAg8AMIICCgKCAgEA5OGmTOe0ciELeaLL1yR5vQ7VgtP97pwHB9KpbE51
# yMo1V/YBf2xK4OK9uT4XYDP/XE/HZveVU3Fa4n5KWv64NmeFRiMMtY0Tz3cywBAY
# 6GB9alKDRLemjkZrBxTzxXb1hlDcwUTIcVxRMTegCjhuje3XD9gmU3w5YQJ6xKr9
# cmmvHaus9ja+NSZk2pg7uhp7M62AW36MEBydUv626GIl3GoPz130/o5Tz9bshVZN
# 7928jaTjkY+yOSxRnOlwaQ3KNi1wjjHINSi947SHJMPgyY9+tVSP3PoFVZhtaDua
# Rr3tpK56KTesy+uDRedGbsoy1cCGMFxPLOJiss254o2I5JasAUq7vnGpF1tnYN74
# kpEeHT39IM9zfUGaRnXNxF803RKJ1v2lIH1+/NmeRd+2ci/bfV+AutuqfjbsNkz2
# K26oElHovwUDo9Fzpk03dJQcNIIP8BDyt0cY7afomXw/TNuvXsLz1dhzPUNOwTM5
# TI4CvEJoLhDqhFFG4tG9ahhaYQFzymeiXtcodgLiMxhy16cg8ML6EgrXY28MyTZk
# i1ugpoMhXV8wdJGUlNi5UPkLiWHzNgY1GIRH29wb0f2y1BzFa/ZcUlFdEtsluq9Q
# BXpsxREdcu+N+VLEhReTwDwV2xo3xwgVGD94q0W29R6HXtqPnhZyacaue7e3Pmri
# Lq0CAwEAAaOCAd0wggHZMBIGCSsGAQQBgjcVAQQFAgMBAAEwIwYJKwYBBAGCNxUC
# BBYEFCqnUv5kxJq+gpE8RjUpzxD/LwTuMB0GA1UdDgQWBBSfpxVdAF5iXYP05dJl
# pxtTNRnpcjBcBgNVHSAEVTBTMFEGDCsGAQQBgjdMg30BATBBMD8GCCsGAQUFBwIB
# FjNodHRwOi8vd3d3Lm1pY3Jvc29mdC5jb20vcGtpb3BzL0RvY3MvUmVwb3NpdG9y
# eS5odG0wEwYDVR0lBAwwCgYIKwYBBQUHAwgwGQYJKwYBBAGCNxQCBAweCgBTAHUA
# YgBDAEEwCwYDVR0PBAQDAgGGMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU
# 1fZWy4/oolxiaNE9lJBb186aGMQwVgYDVR0fBE8wTTBLoEmgR4ZFaHR0cDovL2Ny
# bC5taWNyb3NvZnQuY29tL3BraS9jcmwvcHJvZHVjdHMvTWljUm9vQ2VyQXV0XzIw
# MTAtMDYtMjMuY3JsMFoGCCsGAQUFBwEBBE4wTDBKBggrBgEFBQcwAoY+aHR0cDov
# L3d3dy5taWNyb3NvZnQuY29tL3BraS9jZXJ0cy9NaWNSb29DZXJBdXRfMjAxMC0w
# Ni0yMy5jcnQwDQYJKoZIhvcNAQELBQADggIBAJ1VffwqreEsH2cBMSRb4Z5yS/yp
# b+pcFLY+TkdkeLEGk5c9MTO1OdfCcTY/2mRsfNB1OW27DzHkwo/7bNGhlBgi7ulm
# ZzpTTd2YurYeeNg2LpypglYAA7AFvonoaeC6Ce5732pvvinLbtg/SHUB2RjebYIM
# 9W0jVOR4U3UkV7ndn/OOPcbzaN9l9qRWqveVtihVJ9AkvUCgvxm2EhIRXT0n4ECW
# OKz3+SmJw7wXsFSFQrP8DJ6LGYnn8AtqgcKBGUIZUnWKNsIdw2FzLixre24/LAl4
# FOmRsqlb30mjdAy87JGA0j3mSj5mO0+7hvoyGtmW9I/2kQH2zsZ0/fZMcm8Qq3Uw
# xTSwethQ/gpY3UA8x1RtnWN0SCyxTkctwRQEcb9k+SS+c23Kjgm9swFXSVRk2XPX
# fx5bRAGOWhmRaw2fpCjcZxkoJLo4S5pu+yFUa2pFEUep8beuyOiJXk+d0tBMdrVX
# VAmxaQFEfnyhYWxz/gq77EFmPWn9y8FBSX5+k77L+DvktxW/tM4+pTFRhLy/AsGC
# onsXHRWJjXD+57XQKBqJC4822rpM+Zv/Cuk0+CQ1ZyvgDbjmjJnW4SLq8CdCPSWU
# 5nR0W2rRnj7tfqAxM328y+l7vzhwRNGQ8cirOoo6CGJ/2XBjU02N7oJtpQUQwXEG
# ahC0HVUzWLOhcGbyoYIDVjCCAj4CAQEwggEBoYHZpIHWMIHTMQswCQYDVQQGEwJV
# UzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UEBxMHUmVkbW9uZDEeMBwGA1UE
# ChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMS0wKwYDVQQLEyRNaWNyb3NvZnQgSXJl
# bGFuZCBPcGVyYXRpb25zIExpbWl0ZWQxJzAlBgNVBAsTHm5TaGllbGQgVFNTIEVT
# Tjo2RjFBLTA1RTAtRDk0NzElMCMGA1UEAxMcTWljcm9zb2Z0IFRpbWUtU3RhbXAg
# U2VydmljZaIjCgEBMAcGBSsOAwIaAxUATkEpJXOaqI2wfqBsw4NLVwqYqqqggYMw
# gYCkfjB8MQswCQYDVQQGEwJVUzETMBEGA1UECBMKV2FzaGluZ3RvbjEQMA4GA1UE
# BxMHUmVkbW9uZDEeMBwGA1UEChMVTWljcm9zb2Z0IENvcnBvcmF0aW9uMSYwJAYD
# VQQDEx1NaWNyb3NvZnQgVGltZS1TdGFtcCBQQ0EgMjAxMDANBgkqhkiG9w0BAQsF
# AAIFAOu7lAQwIhgPMjAyNTA0MjkxODA4MDRaGA8yMDI1MDQzMDE4MDgwNFowdDA6
# BgorBgEEAYRZCgQBMSwwKjAKAgUA67uUBAIBADAHAgEAAgIp5zAHAgEAAgITjTAK
# AgUA67zlhAIBADA2BgorBgEEAYRZCgQCMSgwJjAMBgorBgEEAYRZCgMCoAowCAIB
# AAIDB6EgoQowCAIBAAIDAYagMA0GCSqGSIb3DQEBCwUAA4IBAQAt3YU7w2EDRosv
# FzHE9MRY0ZNVLftYYYWBWn7UZDzlATY9Lj5PBff/oTGqS+/3sbk8YoglPeqPFruz
# nZGOxDLk/nXDwCdwRk+lw8FEXQtc+ZvskA7qGu/nCPu2i29Xu/lKbHR62O4WWvXV
# gYaSxfteSiTuAcJk/5w4M23aXF9yBzLcUOp7Rdf56CULqPi8ht9zcaf0FSbag4ev
# jhBT+FwMR8qiEvm4nnKpPN+C7AiWYcn3RURfX9ZBeMXRCCxZ6LjOF96evk01CZuV
# 2tENJBgZU3hxxcwosK6RjHLtRX7UymdoeQlrlhz8lcAUp112VeCGzR0VfIduuumF
# 2quk3mw7MYIEDTCCBAkCAQEwgZMwfDELMAkGA1UEBhMCVVMxEzARBgNVBAgTCldh
# c2hpbmd0b24xEDAOBgNVBAcTB1JlZG1vbmQxHjAcBgNVBAoTFU1pY3Jvc29mdCBD
# b3Jwb3JhdGlvbjEmMCQGA1UEAxMdTWljcm9zb2Z0IFRpbWUtU3RhbXAgUENBIDIw
# MTACEzMAAAH8GKCvzGlahzoAAQAAAfwwDQYJYIZIAWUDBAIBBQCgggFKMBoGCSqG
# SIb3DQEJAzENBgsqhkiG9w0BCRABBDAvBgkqhkiG9w0BCQQxIgQgivws84ZgUP4f
# KxrI3sIGzH8X633Eu22UccRosoBK4d8wgfoGCyqGSIb3DQEJEAIvMYHqMIHnMIHk
# MIG9BCCVQq+Qu+/h/BOVP4wweUwbHuCUhh+T7hq3d5MCaNEtYjCBmDCBgKR+MHwx
# CzAJBgNVBAYTAlVTMRMwEQYDVQQIEwpXYXNoaW5ndG9uMRAwDgYDVQQHEwdSZWRt
# b25kMR4wHAYDVQQKExVNaWNyb3NvZnQgQ29ycG9yYXRpb24xJjAkBgNVBAMTHU1p
# Y3Jvc29mdCBUaW1lLVN0YW1wIFBDQSAyMDEwAhMzAAAB/Bigr8xpWoc6AAEAAAH8
# MCIEIHv+gzzwiQJkX/E97tm4y8nKcKeY3uo4WjljZHFCDKX+MA0GCSqGSIb3DQEB
# CwUABIICAKTPS5sdlSoUOF8C0FHdKwjqidrWtElHI7jScPQP19hFxOE+4uqcZskP
# AxkWspIAGpYtHqwXnUtcwGCba749H8HKkSXYy+OJ9ug2x5yNkAOW9DQaLmcYG38a
# 4pPrwyX+BuqHpC9DC3/6f1S3jdjZMqH2KFkAwxee8J28FPRC6nku42nDoUfxm/tk
# unsFGldFNyUBAfQ7+0BYqt0InskvQ7q6lpCbFznqp777am0GPSXjoh4NuI+mCB25
# UbDW79EgnM2EuAYjv99uoLUw9x8C+/rt5P6rCwRXaZNRSdx3ImrRp6oG5zoqYo2s
# vg0dKsszMdTXU4vxeE510pojhGT2K7o+NBgsdEvZ31gASKdIPu/4jFHgpJ3Cy5oZ
# 4NNpz+Qbn6joQhyW/gDbdmDu1eQOXhZGC5O+uIYYGLhbNDTF3bPnJBIHIlQTLFzb
# tcjFkkDqBQpM8LeEjaf9DQu9PR7AqHrrNsuUdjyAduLqItFuE8Nrvq7f8CdZ0Rw9
# v8R0bkLfrcdWxfrUyd8kKamiEQQ74J0j3x0gh/rx3GZrJ9XeMobAL3mg2sQ65pSB
# C+Ze7f8t7HUPfscy3vDlpPLYXG9ZzL/lL3uMQmtq+Yo8k6C3W9ZbtSGF6qWXghhi
# 7iNWIVsb+PDxGs+Om0vmpg/PqKL6lkuL4Op8fiHcVyjwGa4vjd32
# SIG # End signature block
